import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]

offset = { y = 4 }
size = 18.0

[font.normal]

family = "JetBrains Mono"
style = "Regular"

[window]

padding = { x = 16, y = 8 }

