import = [
  "~/Themes/alacritty-theme/themes/catppuccin_mocha.toml"
]

[font]
offset = { y = 4 }
size = 14.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "None"
opacity = 0.99
padding = { x = 16, y = 16 }
startup_mode = "Fullscreen"

