import = [
  "~/Themes/tokyonight.nvim/extras/alacritty/tokyonight_night.toml"
]

[font]
offset = { y = 4 }
size = 14.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "None"
opacity = 1 
padding = { x = 8, y = 8 }
startup_mode = "Fullscreen"

